### ISSUE TITLE
Database/API issues

### ISSUE THREAD

**Issue by wadupo-git** [reedrunner32/gamegrid-app#11]
I wanted to make a similar app out of this one but i have problem with your API or database because i need to use xampp intstead of whatever you're using....i manage to log in the app but I don't know where to go from there

**Comment by reedrunner32** [comment]
This app was created in collaboration with a backend team. The database and API was created separately with my code only requesting from the backend server. This is not an issue that could be solved directly through my code. If you'd like to known how the backend server was implemented, the database was setup using MongoDB and the server was created using NodeJS. However, I don't recommended that you use my project as a template for what you're trying to create. This was my first attempt at creating an app using Flutter and it is not something I would say I am most proud of. I will also not be updating this repo as my team and I have moved on from this project.
